# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-MSSQL
version:      0.10
version_from: lib/Class/DBI/MSSQL.pm
installdirs:  site
requires:
    Class::DBI:                    0.95
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
