--- #YAML:1.0
name:                Class-DBI-MSSQL
version:             0.121
abstract:            Class::DBI for MSSQL
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Class::DBI:                    0.95
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Ricardo SIGNES <rjbs@cpan.org>
